blank_issues_enabled: false
contact_links:
  - name: ISSUE_TEMPLATE_BUG
    url: https://github.com/DemoTransfer/Java-Guide/blob/master/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_BUG.md
    about: 请在此处提交问题单.
  - name: ISSUE_TEMPLATE_PROPOSAL
    url: https://github.com/DemoTransfer/Java-Guide/blob/master/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_PROPOSAL.md
    about: 请在此处提交需求单.
